obj-m=file.o
PWD=/home/nagalakshmi/Documents/test/nested_makefile/level11/level22/level33/

all:
	make -C /lib/modules/5.17.2/build/ M=$(PWD) modules
clean:
	make -C /lib/modules/5.17.2/build M=$(PWD) clean
